version: "3.8"
services:
  shopsurfer_auth_db:
    image: postgres
    volumes:
      # - ./sql:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5431:5432
    env_file: .env
    container_name: shopsurfer_auth_db

    networks:
      - my_network

  shopsurfer_auth:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./app:/app
    ports:
      - 8001:8000
    image: shopsurfer_auth:latest
    container_name: shopsurfer_auth
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - shopsurfer_auth_db

    networks:
      - my_network

networks:
  my_network:
    external: true
